POST https://crud-api-express.onrender.com/api/v1/users
Content-Type: application/json

{
  "firstName": "Gabriela",
  "lastName": "Jimenez",
  "email": "gabriela@hotmail.com",
  "password": "gabriela123",
  "birthday": "1999/11/16"
}