POST https://crud-api-express.onrender.com/api/v1/users
Content-Type: application/json

{
  "firstName": "Miranda",
  "lastName": "Muñiz",
  "email": "miranda@hotmail.com",
  "password": "miranda123",
  "birthday": "2017-01-24"
}