DELETE http://localhost:8001/api/v1/tasks/5210757f-aede-43b6-947f-d170ab25aad0
Content-Type: application/json

###

# DELETE https://crud-api-express.onrender.com/api/v1/tasks/3c002961-adc5-48ff-bcfb-94681f94e437
# Content-Type: application/json

